# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBCommand.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import PBMessage_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBCommand.proto',
  package='netty',
  serialized_pb='\n\x0fPBCommand.proto\x12\x05netty\x1a\x0fPBMessage.proto\"@\n\x08\x43\x32SLogin\x12\x10\n\x08userName\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\x12\x10\n\x08\x64\x65viceID\x18\x03 \x02(\t\":\n\x08S2CLogin\x12\r\n\x05token\x18\x01 \x02(\t\x12\x1f\n\x08userInfo\x18\x02 \x02(\x0b\x32\r.netty.PBUser\"\r\n\x0b\x43\x32SUserInfo\".\n\x0bS2CUserInfo\x12\x1f\n\x08userInfo\x18\x01 \x02(\x0b\x32\r.netty.PBUser\"\r\n\x0b\x43\x32SHeroInfo\".\n\x0bS2CHeroInfo\x12\x1f\n\x08heroList\x18\x01 \x03(\x0b\x32\r.netty.PBHeroB%\n\x18\x63om.ease.nogame.protobufB\tPBCommand')




_C2SLOGIN = _descriptor.Descriptor(
  name='C2SLogin',
  full_name='netty.C2SLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userName', full_name='netty.C2SLogin.userName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='netty.C2SLogin.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceID', full_name='netty.C2SLogin.deviceID', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=107,
)


_S2CLOGIN = _descriptor.Descriptor(
  name='S2CLogin',
  full_name='netty.S2CLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='netty.S2CLogin.token', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userInfo', full_name='netty.S2CLogin.userInfo', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=109,
  serialized_end=167,
)


_C2SUSERINFO = _descriptor.Descriptor(
  name='C2SUserInfo',
  full_name='netty.C2SUserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=169,
  serialized_end=182,
)


_S2CUSERINFO = _descriptor.Descriptor(
  name='S2CUserInfo',
  full_name='netty.S2CUserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userInfo', full_name='netty.S2CUserInfo.userInfo', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=184,
  serialized_end=230,
)


_C2SHEROINFO = _descriptor.Descriptor(
  name='C2SHeroInfo',
  full_name='netty.C2SHeroInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=232,
  serialized_end=245,
)


_S2CHEROINFO = _descriptor.Descriptor(
  name='S2CHeroInfo',
  full_name='netty.S2CHeroInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heroList', full_name='netty.S2CHeroInfo.heroList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=247,
  serialized_end=293,
)

_S2CLOGIN.fields_by_name['userInfo'].message_type = PBMessage_pb2._PBUSER
_S2CUSERINFO.fields_by_name['userInfo'].message_type = PBMessage_pb2._PBUSER
_S2CHEROINFO.fields_by_name['heroList'].message_type = PBMessage_pb2._PBHERO
DESCRIPTOR.message_types_by_name['C2SLogin'] = _C2SLOGIN
DESCRIPTOR.message_types_by_name['S2CLogin'] = _S2CLOGIN
DESCRIPTOR.message_types_by_name['C2SUserInfo'] = _C2SUSERINFO
DESCRIPTOR.message_types_by_name['S2CUserInfo'] = _S2CUSERINFO
DESCRIPTOR.message_types_by_name['C2SHeroInfo'] = _C2SHEROINFO
DESCRIPTOR.message_types_by_name['S2CHeroInfo'] = _S2CHEROINFO

class C2SLogin(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _C2SLOGIN

  # @@protoc_insertion_point(class_scope:netty.C2SLogin)

class S2CLogin(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S2CLOGIN

  # @@protoc_insertion_point(class_scope:netty.S2CLogin)

class C2SUserInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _C2SUSERINFO

  # @@protoc_insertion_point(class_scope:netty.C2SUserInfo)

class S2CUserInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S2CUSERINFO

  # @@protoc_insertion_point(class_scope:netty.S2CUserInfo)

class C2SHeroInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _C2SHEROINFO

  # @@protoc_insertion_point(class_scope:netty.C2SHeroInfo)

class S2CHeroInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S2CHEROINFO

  # @@protoc_insertion_point(class_scope:netty.S2CHeroInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\030com.ease.nogame.protobufB\tPBCommand')
# @@protoc_insertion_point(module_scope)
