package com.ease.nogame.domain;

// Generated 2015-1-8 14:04:07 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private long id;
	private Date createTime;
	private Date accessTime;
	private String userName;
	private String password;
	private String token;

	public Account() {
	}

	public Account(long id, Date createTime, Date accessTime, String userName,
			String password) {
		this.id = id;
		this.createTime = createTime;
		this.accessTime = accessTime;
		this.userName = userName;
		this.password = password;
	}

	public Account(long id, Date createTime, Date accessTime, String userName,
			String password, String token) {
		this.id = id;
		this.createTime = createTime;
		this.accessTime = accessTime;
		this.userName = userName;
		this.password = password;
		this.token = token;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getAccessTime() {
		return this.accessTime;
	}

	public void setAccessTime(Date accessTime) {
		this.accessTime = accessTime;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
